name: Code Quality
on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Generate lock file
        run: uv lock --locked

  linting:
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint the code
        run: uvx ruff check .

  formatting:
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check code formatting
        run: uvx ruff format --check .

  type_consistency:
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check code quality with Flake8
        run: |
          echo "Running Flake8 with custom configuration"
          uv run flake8 --config=.flake8 .

  tests:
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run tests
        run: uv run pytest -v --durations=0

  build:
    runs-on: ubuntu-latest
    needs: [linting, formatting, type_consistency, tests]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build the project
        run: uv build
